name: Build and deploy .NET 8 app to Azure Web App - ozandemo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore application/learningapp.sln

      - name: Build
        run: dotnet build application/learningapp.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish application/learningapp/learningapp.csproj --configuration Release --no-build --output ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
          path: ./publish
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D560335C4DF64B078DB944A66E55EF43 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F875A1247B0F42C1B7B449E59E8DD49A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_24E956FB91E249F291A70B64700CB205 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ozandemo'
          slot-name: 'Production'
          package: ./publish

